OPENROUTER_API_KEY=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
LOCAL_MODEL_NAME=ai/qwen2.5
REMOTE_MODEL_NAME=qwen/qwen3-30b-a3b
LOCAL_BASE_URL=http://model-runner.docker.internal/engines/llama.cpp/v1
REMOTE_BASE_URL=https://openrouter.ai/api/v1
